### ISSUE TITLE
Allow CSV download without authenticating

### ISSUE THREAD

**Issue by agprice** [ucsb-cs56-w20/ucsb-courses-search#110]
As a user I want to download a general search result CSV without having to log in.

Acceptance Criteria:
* Can download CSV without logging in

**Comment by troylee24** [comment]
The Oauth authorization requires a login as per "Application.java". Controllers such as "Membership Service" and also the controller advice "AuthControllerAdvice.java" both show the process of deeming a user as a member or not. By default, the user (if not logged in) is set as "Guest." Perhaps instead of completely evading a login process, a temporary profile can be logged into so the user can have at least "user privileges."
