### ISSUE TITLE
Add CSV download option to the personal schedule

### ISSUE THREAD

**Issue by agprice** [ucsb-cs56-w20/ucsb-courses-search#113]
As a user I want to be able to download my personal schedule as a CSV.

Acceptance Criteria:
* Personal schedule is downloadable as a CSV file
* Can press a button to download CSV

**Comment by dariansung** [comment]
To add the button to the course schedule page, it seems that there need to be a <button> element added to src/main/resources/templates/courseschedule/index.html after the <table> that will perform a download CSV function. Because the page is formatted differently from the search result pages, I believe another downloader will have to be written for the schedule page. This would be added to the src/main/java/edu/ucsb/cs56/ucsb_courses_search/downloaders directory and would have similar functionality to the CoursePageToCSV.java file in the same directory, only reappropriated to handle the information on the schedule page.
