### ISSUE TITLE
Display a quarter's pass times and add deadlines in the personal schedule page

### ISSUE THREAD

**Issue by agprice** [ucsb-cs56-w20/ucsb-courses-search#120]
As a user, I want to see pass times and add deadlines in the personal schedule page.

Acceptance Criteria
- [x] Deadlines and pass times in a consistently visible location.  
- [ ] Include pass times for each class standing
           -could not get data for this from api

**Comment by isaaclaam** [comment]
In order to work on this story we must edit the file ucsb-courses-search/src/main/resources/templates/courseschedule/index.html.
This is the file that displays your personal course schedule, as a result this file must definitely be modified in order to display other things like the quarter's pass times that we intend to add.
