### ISSUE TITLE
Rename "CS Department Classroom Search" to "Search by Classrooms"

### ISSUE THREAD

**Issue by kerem-signifai** [ucsb-cs56-w20/ucsb-courses-search#134]

**Comment by kimiamajd** [comment]
In file /src/main/resources/templates/csdept/classroom/fragments/title.html
Must change 
"Search For Courses in CS Department Controlled Classrooms" to "Search by Classrooms" to change the header of the search by classroom page. 

In addition "This page allows you to search for all courses offered in CS department controlled classrooms in a specific quarter" should be changed to an appropriate message. 

Lastly, in the file src/main/resources/templates/fragments/bootstrap_nav_header.html
I would change "CS Department" from a Nav-item-dropdown to a nav-item because it is not necessary to have a drop down menu since there is only one item in the list. I would then rename it to "Search by Classroom".

**Comment by finnderman1** [comment]
> Lastly, in the file src/main/resources/templates/fragments/bootstrap_nav_header.html
> I would change "CS Department" from a Nav-item-dropdown to a nav-item because it is not necessary to have a drop down menu since there is only one item in the list. I would then rename it to "Search by Classroom".

I am not convinced that this is a good idea, because we are unaware if there are other teams working on items for this drop drown menu.
