### ISSUE TITLE
As a user, I would like to be able to search for the full classroom name instead of the abbreviation that GOLD uses.

### ISSUE THREAD

**Issue by kerem-signifai** [ucsb-cs56-w20/ucsb-courses-search#138]

**Comment by Neemers** [comment]
In  ucsb-courses-search/src/main/java/edu/ucsb/cs56/ucsb_courses_search/model/search/SearchByCourse.java since we use the UCSB API to allow searching for courses using abbreviation, we can also add a vector of class names in full length; this way the user can use either the abbreviation or the full name of the class.

**Comment by xitsleena** [comment]
Using a JSON file that has corresponding abbreviations and full classroom names, we can SearchByClassroom.java (rename from CS department?) and have an or statement for the search.
