### ISSUE TITLE
As I user I want the course information popup to include the course description.

### ISSUE THREAD

**Issue by ryan8xia** [ucsb-cs56-w20/ucsb-courses-search#145]

**Comment by jairobedolla** [comment]
Acceptance Criteria: we display the corresponding course description in the popup window we create for each class.

**Comment by jairobedolla** [comment]
In order to solve this issue, I would need to write and implement code that utilizes the API in order to retrieve the actual description of the requested course and store it into a string and then in the HTML file for our popup window write in code that will actually display the string with the description
